base_classes = {
    "barbarian": {"uuid": "d8cadb42-0ff9-4049-afaf-e5d78d06a399", "level": 3},
    "bard": {"uuid": "92cd50b6-eb1b-4824-8adb-853e90c34c90", "level": 3},
    "cleric": {"uuid": "114e7aee-d1d4-4371-8d90-8a2080592faf", "level": 1},
    "druid": {"uuid": "457d0a6e-9da8-4f95-a225-18382f0e94b5", "level": 2},
    "fighter": {"uuid": "721dfac3-92d4-41f5-b773-b7072a86232f", "level": 3},
    "monk": {"uuid": "c4598bdb-fc07-40dd-a62c-90cc138bd76f", "level": 3},
    "paladin": {"uuid": "ff4d9497-023c-434a-bd14-82fc367e991c", "level": 1},
    "ranger": {"uuid": "36be18ba-23db-4dff-bfa6-ae105ce43144", "level": 3},
    "rogue": {"uuid": "e8b1eab0-ef11-40a2-8a0b-cee8d062bf2a", "level": 3},
    "sorcerer": {"uuid": "784001e2-c96d-4153-beb6-2adbef5abc92", "level": 1},
    "warlock": {"uuid": "b4225a4b-4bbe-4d97-9e3c-4719dbd1487c", "level": 1},
    "wizard": {"uuid": "a865965f-501b-46e9-9eaa-7748e8c04d09", "level": 2},
}

subclasses = {
    "barbarian": [
        "Ancestral Guardian",
        "Battlerager",
        "Beast",
        "Giant",
        "Juggernaut",
        "Storm Herald",
        "Zealot",
    ],
    "bard": [
        "College of Creation",
        "College of Eloquence",
        "College of Glamour",
        "College of Spirits",
        "College of Tragedy",
        "College of Whispers",
    ],
    "cleric": [
        "Arcana Domain",
        "Blood Domain",
        "Death Domain",
        "Forge Domain",
        "Grave Domain",
        "Moon Domain",
        "Order Domain",
        "Peace Domain",
        "Twilight Domain",
    ],
    "druid": [
        "Circle of Dreams",
        "Circle of Stars",
        "Circle of the Blighted",
        "Circle of the Shepherd",
        "Circle of Wildfire",
    ],
    "fighter": [
        "Arcane Archer",
        "Cavalier",
        "Echo Knight",
        "Psi Warrior",
        "Purple Dragon Knight",
        "Rune Knight",
        "Samurai",
    ],
    "monk": [
        "Way of Mercy",
        "Way of the Ascendant Dragon",
        "Way of the Astral Self",
        "Way of the Cobalt Soul",
        "Way of the Drunken Master",
        "Way of the Kensei",
        "Way of the Long Death",
        "Way of the Sun Soul",
    ],
    "paladin": [
        "Oath of Conquest",
        "Oath of Glory",
        "Oath of Redemption",
        "Oath of the Crown",
        "Oath of the Open Sea",
        "Oath of the Watchers",
    ],
    "ranger": [
        "Drakewarden",
        "Fey Wanderer",
        "Horizon Walker",
        "Monster Slayer",
        "Swarmkeeper",
    ],
    "rogue": [
        "Inquisitive",
        "Mastermind",
        "Phantom",
        "Scout",
        "Soulknife",
        "Swashbuckler",
    ],
    "sorcerer": [
        "Aberrant Mind",
        "Clockwork Soul",
        "Divine Soul",
        "Lunar Sorcery",
        "Runechild",
        "Shadow Magic",
    ],
    "warlock": [
        "The Celestial",
        "The Fathomless",
        "The Genie",
        "The Hexblade",
        "The Undead",
        "The Undying",
    ],
    "wizard": [
        "Bladesinging",
        "Blood Magic",
        "Chronurgy Magic",
        "Graviturgy Magic",
        "Order of Scribes",
        "War Magic",
    ],
}
